#!/bin/env bash
n=0
m=0
o=0
p=0

 while ((n<=2));do
     while ((m<=9));do
	 while ((n<=2 && m<=3));do
         while ((o<=5));do
             while ((p <= 9));do
       echo "$n"
       echo "$m"
       echo ":"
       echo "$o"
       echo "$p"
       printf"\n"
      ((p++))
       done
             ((o++))
             ((p=0))
	     done
         ((m++))
         ((o=0))
	 done
     ((n++))
     ((m=0))
     done
     
 done
 
	       
     
